version: "3.3"
services:
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    depends_on:
      - main

  main:
    build:
      context: .
      dockerfile: main/Dockerfile
    ports:
      - "8000:8000"